app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    posts=db.relationship('Post',backref='user',lazy='dynamic')
    comments=db.relationship('Comment',backref='user',lazy='dynamic')
    pass_secure = db.Column(db.String(255))
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Post(db.Model):
    __tablename__= 'posts' 
    id = db.Column(db.Integer,primary_key = True)
    content = db.Column(db.String(255))
    users_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments=db.relationship('Comment',backref='post',lazy='dynamic')
    def __repr__(self):
        return f'User {self.content}'

    def delete_post(self):
       db.session.delete(self)
       db.session.commit()

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    names = db.Column(db.String(255), index=True)
    comment = db.Column(db.String(255))
    posts_id = db.Column(db.Integer,db.ForeignKey('posts.id'))
    users_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    def __repr__(self):
        return f'User {self.comment}'
    
    def delete_comment(self):
       db.session.delete(self)
       db.session.commit()

class Subscribe(db.Model):
    __tablename__ = 'subscribers'
    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255),unique = True,index = True)
    def __repr__(self):
        return f'User {self.email}'

class Quote:

    def __init__(self,id,author,quote):
        self.id =id
        self.author = author
        self. quote = quote

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class ReviewForm(FlaskForm):

    title = StringField('Review title',validators=[Required()])
    review = TextAreaField('Movie review', validators=[Required()])
    submit = SubmitField('Submit')
    
class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')
class PostForm(FlaskForm):
     content = TextAreaField('write Your Post', validators=[Required()])
     submit = SubmitField('Submit!')

class CommentsForm(FlaskForm):
    names = TextAreaField('names', validators=[Required()])
    comment = TextAreaField('Comment', validators=[Required()])
    submit = SubmitField('SUBMIT')  

class SubForm(FlaskForm):
    email = TextAreaField('input your email', validators=[Required()])
    submit = SubmitField('SUBMIT')  
class UpdatePostForm(FlaskForm):
    content=TextAreaField('Content',validators = [Required()])
    submit=SubmitField('SUBMIT')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

# login_manager = LoginManager()
# login_manager.session_protection = 'strong'
# login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .request import configure_request
    configure_request(app)
    # Will add the views and forms

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import ReviewForm,UpdateProfile,PostForm,CommentsForm,SubForm,UpdatePostForm
from ..models import User,Post,Comment,Subscribe
from flask_login import login_required,current_user
from .. import db
from ..request import get_quote
from ..email import mail_message


@main.route('/')
def index():
    
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home'
    quote=get_quote()
    # print(quote)
    post=Post.query.all()
    return render_template('index.html', title = title, post=post,quote=quote)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/post/new', methods=['GET','POST'])
@login_required
def create_posts():
    form = PostForm()
    subscribers=Subscribe.query.all()
    if form.validate_on_submit():
        content=form.content.data
        new_post=Post(content = content,user=current_user)

        db.session.add(new_post)
        db.session.commit()
        for subscriber in subscribers:
          mail_message("hello! there is new post","email/notification",subscriber.email)


        return redirect(url_for('main.index'))

    return render_template('post.html',form = form) 

@main.route('/edit/post/<int:id>',methods= ['GET','POST'])
@login_required
def update_post(id):
   post=Post.query.filter_by(id=id).first()
   if post is None:
        abort(404)

   form=UpdatePostForm()
   if form.validate_on_submit():
        #  post.title=form.title.data
         post.content=form.content.data

         db.session.add(post)
         db.session.commit()

         return redirect(url_for('main.index'))
   return render_template('update_post.html',form=form)

@main.route('/delete/post/<int:id>', methods = ['GET', 'POST'])
@login_required
def delete_post(id):
    post=Post.query.filter_by(id=id).first()
    title = 'Home'
    
    if post is not None:
       post.delete_post()
       return redirect(url_for('main.index'))
    return render_template('index.html', title = title, post=post,quote=quote)

@main.route('/comment/new/<int:id>', methods=['GET','POST'])
@login_required
def comments(id):
    form = CommentsForm()
    if form.validate_on_submit():
        names=form.names.data
        comment=form.comment.data
        new_comment=Comment(comment=comment,names=names ,posts_id = id,user=current_user)
        

        db.session.add(new_comment)
        db.session.commit()
    comment=Comment.query.filter_by(posts_id=id).all()

    return render_template('comment.html',comment=comment,form = form)

@main.route('/delete/comment/<int:id>', methods = ['GET', 'POST'])
@login_required
def delete_comment(id):
    form = CommentsForm()
    comment=Comment.query.filter_by(id=id).first()
 

    if comment is not None:
       comment.delete_comment()
       return redirect(url_for('main.index'))

    return render_template('comment.html',form = form)

@main.route('/subscriber/new/', methods=['GET','POST'])
def subscribe():
    form=SubForm()
    if form.validate_on_submit():
        email=form.email.data
        new_subscriber=Subscribe(email=email)

        db.session.add(new_subscriber)
        db.session.commit()
        mail_message("Thank you for subscribing","email/subscribing",new_subscriber.email)
        
        return redirect(url_for('main.index'))

    return render_template('subscriber.html',form = form)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> Welcome to one minute pitches </title>
    {% endif %}
</head>

<body>
    <!-- Content block -->
    {% extends 'bootstrap/base.html'%}
    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock %}

    {% block content %}

    {% endblock%}
</body>

</html>

app/templates/comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container">

    <div>

        {{ wtf.quick_form(form) }}
    </div>
    <div class="anna">
        <div class="well-lg">
            {% for vida in comment %}
            <p id="sub"><strong>{{vida.names}}</strong> commented:</p>
            <p>{{vida.comment}}</p>
            <a href="{{url_for('main.delete_comment',id=vida.id)}}"><button id="mamie">Delete</button></a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock%}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h2>OOps, look like you are facing an issue can't find the page requested</h2>
{% endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

<body>
    {% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    {% endblock %}

    {% block content %}

    <h1>Welcome To our <strong>Blogging Website!</strong></h1>
    <h2>
        <a href={{ url_for('main.create_posts') }}>
            <button id="mamie">addPost</button></a>

    </h2>

    <div class="container">
        <blockquote class="text-center text-lg">
            <h2> Random Quotes</h2>
            <p>{{quote.quote}}</p>
            <p class="sab">Author: {{quote.author}}</p>

        </blockquote>
        <div class="nini">
            {%for vida in post%}
            <div class="bella">
                <p>{{vida.names}}</p>
                <p>{{vida.content}}</p>
                <a href="/comment/new/{{vida.id}}"><button id="mamie">comment</button></a>
                <a href="{{url_for('main.update_post',id=vida.id)}}"><button id="mamie">Edit</button></a>
                <a href="{{url_for('main.delete_post',id=vida.id)}}"><button id="mamie">Delete</button></a>
            </div>
            {% endfor%}


        </div>

    </div>
    {% endblock%}
</body>

app/templates/macros.html
{% macro displayPitches(pitches) %}

{% for pitch in pitches %}
{% if pitch.user.profile_pic_path %}
<img src="{{pitch.user.profile_pic_path}}" alt="Show image" height="45">
<p>{{pitch.user.username}}</p>

<h4>{{pitch.content}}</h4>
<button>Upvote</button>
<button>Downvote</button>
<!-- {% else %}
<img src="static/photos/no dp.png" alt="no pp">
<p>{{pitch.user.username}}</p>
<h4>{{pitch.user.content}}</h4>
<button>Upvote</button>
<button>Downvote</button>
{% endif %} -->

{% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- <a class="navbar-brand" href="/">POSTS</a> -->
            <a class="navbar-brand" href="{{url_for('main.subscribe')}}">SUBSCRIBE</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">HOME/POSTS</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <!-- <li><a href="{{url_for('auth.logout')}}">Sign out</a></li> -->
                {% else %}
                <!-- <li><a href="{{url_for('auth.login')}}">Sign in</a></li> -->
                {%endif%}
            </ul>
        </div>
    </div>
</div>

app/templates/new_review.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">

    <div class="col-md-8">

        <img src="{{pitch.poster}}" alt="{{pitch.title}}" class="img-responsive">
    </div>

    <div class="col-md-4">

        {{ wtf.quick_form(review_form) }}
    </div>

</div>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}

{% import "bootstrap/wtf.html" as wtf %}
<div id="nini">
    {% block content %}
    <div class="container">

        <div>
            {{wtf.quick_form(form)}}
        </div>
    </div>
    {% endblock%}
</div>

app/templates/post.html
{% extends 'base.html'%}

{% import "bootstrap/wtf.html" as wtf %}
<div id="nini">
    {% block content %}
    <div class="container">

        <div>
            {{wtf.quick_form(form)}}
        </div>
    </div>
    {% endblock%}
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
{% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/subscriber.html
{% extends 'base.html'%}

{% import "bootstrap/wtf.html" as wtf %}
<div id="nini">
    {% block content %}
    <div class="container">

        <div>
            {{wtf.quick_form(form)}}
        </div>
    </div>
    {% endblock%}
</div>

app/templates/update_post.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}

</div>

{% endblock %}